### ISSUE TITLE
the root CLI user has to run api

### ISSUE THREAD

**Issue by werdnanoslen** [werdnanoslen/mobile-map-io#25]

**Comment by werdnanoslen** [comment]
Running server on default settings without root, when accessing the /reports endpoint, the following error occurs and crashes server:
```
/var/www/mobile-map-io/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'query' of undefined
    at /var/www/mobile-map-io/api/server.js:68:12
    at /var/www/mobile-map-io/api/server.js:26:13
    at Handshake.onConnect (/var/www/mobile-map-io/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.Sequence.end (/var/www/mobile-map-io/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Handshake.ErrorPacket (/var/www/mobile-map-io/node_modules/mysql/lib/protocol/sequences/Handshake.js:105:8)
    at Protocol._parsePacket (/var/www/mobile-map-io/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/var/www/mobile-map-io/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/var/www/mobile-map-io/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/mobile-map-io/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:77:13)

npm ERR! Linux 4.8.0-54-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! mobile-map-io@1.0.0 start: `node api/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mobile-map-io@1.0.0 start script 'node api/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mobile-map-io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node api/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mobile-map-io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mobile-map-io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mobile-map-io/npm-debug.log
```
see [L68](https://github.com/werdnanoslen/mobile-map-io/blob/60ff565bd2f4c3fab3f2ccd49c57ced5a1593e9c/api/server.js#L68) and [L26](https://github.com/werdnanoslen/mobile-map-io/blob/60ff565bd2f4c3fab3f2ccd49c57ced5a1593e9c/api/server.js#L26)

**Comment by werdnanoslen** [comment]
For the sake of this boilerplate, the user should know this is for local prototyping only. If they're new, they at least have a root user, and if they're experienced they should know how to create and manage a new user. Either way, for the sake of simple instructions, I'm going to assume the user is root https://github.com/werdnanoslen/mobile-map-io/commit/beca93615d3544e0699f66c8be1c3b635020be91
